# Generated by Django 5.1.5 on 2025-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_products',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='pay',
            field=models.FloatField(max_length=14),
        ),
    ]
